plugins {
    alias(libs.plugins.kotlin.multiplatform) apply false
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.detekt)
    alias(libs.plugins.spotless)
}

detekt {
    buildUponDefaultConfig = true
    allRules = false
    config.setFrom("$rootDir/detekt.yml")
    source.setFrom(
        fileTree("core/src") { include("**/*.kt") },
        fileTree("kotest/src") { include("**/*.kt") },
        fileTree("annotations/src") { include("**/*.kt") },
        fileTree("ksp/src") { include("**/*.kt") },
    )
}

spotless {
    kotlin {
        target("**/*.kt")
        targetExclude("**/build/**")
        ktlint("1.5.0").editorConfigOverride(
            mapOf(
                "ktlint_standard_package-name" to "disabled",
                "ktlint_standard_filename" to "disabled",
                "ktlint_standard_no-wildcard-imports" to "disabled",
                "ktlint_standard_function-naming" to "disabled",
            ),
        )
    }
    kotlinGradle {
        target("**/*.kts")
        targetExclude("**/build/**")
        ktlint("1.5.0")
    }
}

tasks.register("installGitHooks") {
    description = "Configures git to use .githooks/ directory"
    doLast {
        exec { commandLine("git", "config", "core.hooksPath", ".githooks") }
    }
}

tasks.named("prepareKotlinBuildScriptModel") {
    dependsOn("installGitHooks")
}

// Feature-file embedding — shared across modules whose tests need to read .feature files
// without runtime IO (e.g. iOS simulator sandbox). Each module gets its own GeneratedFeatures
// object populated with everything in src/commonTest/resources.
configure(listOf(project(":core"), project(":kotest"))) {
    plugins.withId("org.jetbrains.kotlin.multiplatform") {
        val featureResourcesDir = layout.projectDirectory.dir("src/commonTest/resources")
        val generatedFeaturesDir = layout.buildDirectory.dir("generated/features/commonTest/kotlin")

        val generateTestFeatures =
            tasks.register("generateTestFeatures") {
                description = "Embeds .feature files into GeneratedFeatures.kt so tests can run without runtime IO."
                inputs.dir(featureResourcesDir).withPathSensitivity(org.gradle.api.tasks.PathSensitivity.RELATIVE)
                outputs.dir(generatedFeaturesDir)

                doLast {
                    val outFile =
                        generatedFeaturesDir
                            .get()
                            .file("io/mcol/behave/generated/GeneratedFeatures.kt")
                            .asFile
                    outFile.parentFile.mkdirs()

                    val baseDir = featureResourcesDir.asFile
                    val entries =
                        baseDir
                            .walkTopDown()
                            .filter { it.isFile && it.extension == "feature" }
                            .sortedBy { it.invariantSeparatorsPath }
                            .map { file ->
                                val path = file.relativeTo(baseDir).invariantSeparatorsPath
                                val literal = kotlinStringLiteral(file.readText())
                                "    FeatureRegistry.register(${kotlinStringLiteral(path)}, $literal)"
                            }.joinToString("\n")

                    outFile.writeText(
                        """
                        // Auto-generated by :${project.name}:generateTestFeatures. Do not edit.
                        package io.mcol.behave.generated

                        import io.mcol.behave.runner.FeatureRegistry

                        object GeneratedFeatures {
                            fun install() {
                        $entries
                            }
                        }

                        """.trimIndent(),
                    )
                }
            }

        extensions
            .getByType(org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension::class.java)
            .sourceSets
            .named("commonTest") {
                kotlin.srcDir(generateTestFeatures)
            }
    }
}

fun kotlinStringLiteral(value: String): String {
    val escaped =
        value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\$", "\\\$")
            .replace("\r", "\\r")
            .replace("\n", "\\n")
            .replace("\t", "\\t")
    return "\"$escaped\""
}
