import org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeHostTest

plugins {
    alias(libs.plugins.kotlin.multiplatform)
}

group = "io.mcol.kotlin-behave"
version = "0.1.0"

val featureResourcesDir = layout.projectDirectory.dir("src/commonTest/resources")
val generatedFeaturesDir = layout.buildDirectory.dir("generated/features/commonTest/kotlin")

val generateTestFeatures by tasks.registering {
    description = "Embeds .feature files into GeneratedFeatures.kt so tests can run without runtime IO."
    inputs.dir(featureResourcesDir).withPathSensitivity(org.gradle.api.tasks.PathSensitivity.RELATIVE)
    outputs.dir(generatedFeaturesDir)

    doLast {
        val outFile =
            generatedFeaturesDir
                .get()
                .file("io/mcol/behave/generated/GeneratedFeatures.kt")
                .asFile
        outFile.parentFile.mkdirs()

        val baseDir = featureResourcesDir.asFile
        val entries =
            baseDir
                .walkTopDown()
                .filter { it.isFile && it.extension == "feature" }
                .sortedBy { it.invariantSeparatorsPath }
                .map { file ->
                    val path = file.relativeTo(baseDir).invariantSeparatorsPath
                    val literal = kotlinStringLiteral(file.readText())
                    "    FeatureRegistry.register(${kotlinStringLiteral(path)}, $literal)"
                }.joinToString("\n")

        outFile.writeText(
            """
            // Auto-generated by :core:generateTestFeatures. Do not edit.
            package io.mcol.behave.generated

            import io.mcol.behave.runner.FeatureRegistry

            object GeneratedFeatures {
                fun install() {
            $entries
                }
            }

            """.trimIndent(),
        )
    }
}

kotlin {
    jvm()
    js {
        nodejs()
    }
    iosX64()
    iosArm64()
    iosSimulatorArm64()
    macosX64()
    macosArm64()
    linuxX64()

    sourceSets {
        commonTest {
            kotlin.srcDir(generateTestFeatures)
            dependencies {
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.test)
            }
        }
    }
}

// Native host tests (linuxX64, macosX64, macosArm64) read .feature files relative to cwd.
// Embedded GeneratedFeatures covers the iOS simulator sandbox case; both paths active means
// tests pass whether or not GeneratedFeatures.install() has been called.
tasks.withType<KotlinNativeHostTest>().configureEach {
    workingDir = file("src/commonTest/resources").absolutePath
}

fun kotlinStringLiteral(value: String): String {
    val escaped =
        value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\$", "\\\$")
            .replace("\r", "\\r")
            .replace("\n", "\\n")
            .replace("\t", "\\t")
    return "\"$escaped\""
}
