package io.mcol.behave.ksp

/**
 * Generates Kotlin source text for the step definitions interface.
 */
internal object CodeGenerator {

    data class TypeMapping(
        val placeholder: String,   // e.g. "label" for {label}, or "" for field-based
        val typeName: String,      // fully qualified type name
        val fields: List<String>,  // field names for multi-field grouping; empty for placeholder mode
    )

    data class StepParam(
        val name: String,
        val typeName: String,  // Kotlin type name (e.g. "String", "Int", "List<CatRow>")
    )

    data class GeneratedStep(
        val methodName: String,
        val params: List<StepParam>,
        val stepExpression: String,  // regex-escaped pattern for the companion
        val originalKeyword: String,
        val originalText: String,
        val castParams: Map<Int, String> = emptyMap(), // param index → original narrow type (e.g. "Int")
    )

    data class GeneratedRowClass(
        val name: String,
        val params: List<StepParam>,
        val shouldEmit: Boolean = true,  // false for user-defined types that already exist
    )

    data class GeneratedInterface(
        val packageName: String,
        val interfaceName: String,      // e.g. "LoginStepsSpec"
        val implementingClassName: String, // e.g. "LoginSteps"
        val featurePath: String,         // e.g. "features/login.feature"
        val generateTest: Boolean,       // when false, skip val + test class generation
        val steps: List<GeneratedStep>,
        val rowClasses: List<GeneratedRowClass>,
    )

    fun render(iface: GeneratedInterface): String = buildString {
        appendLine("// Generated by kotlin-behave KSP — do not edit")
        appendLine("package ${iface.packageName}")
        appendLine()
        appendLine("import io.kotest.core.spec.style.FreeSpec")
        appendLine("import io.mcol.behave.kotest.gherkin")
        appendLine()

        // Row classes first (only emit auto-generated ones, not user-defined)
        for (row in iface.rowClasses.filter { it.shouldEmit }) {
            append("data class ${row.name}(")
            append(row.params.joinToString(", ") { "val ${it.name}: ${it.typeName}" })
            appendLine(")")
            appendLine()
        }

        appendLine("interface ${iface.interfaceName} {")
        appendLine()

        for (step in iface.steps) {
            appendLine("    // ${step.originalKeyword} ${step.originalText}")
            if (step.params.isEmpty()) {
                appendLine("    suspend fun ${step.methodName}()")
            } else {
                val paramList = step.params.joinToString(", ") { "${it.name}: ${it.typeName}" }
                appendLine("    suspend fun ${step.methodName}($paramList)")
            }
            appendLine()
        }

        appendLine("    companion object {")
        appendLine("        fun steps(factory: () -> ${iface.interfaceName}): io.mcol.behave.steps.StepDefinitions<${iface.interfaceName}> =")
        appendLine("            io.mcol.behave.steps.steps(factory) {")

        for (step in iface.steps) {
            val keyword = step.originalKeyword
            val widenedExpr = widenStepExpression(step.stepExpression, step.castParams, step.params)
            val expr = widenedExpr.replace("\"", "\\\"")
            if (step.params.isEmpty()) {
                appendLine("                $keyword(\"$expr\") { ctx.${step.methodName}() }")
            } else {
                renderStepCall(step, iface.rowClasses, expr)
            }
        }

        appendLine("            }")
        appendLine("    }")
        appendLine("}")
        appendLine()

        if (iface.generateTest) {
            // Generated step definitions instance
            val baseName = iface.implementingClassName.removeSuffix("Steps")
            val stepsVarName = "generated${baseName}Steps"
            appendLine("val $stepsVarName = ${iface.interfaceName}.steps { ${iface.implementingClassName}() }")
            appendLine()

            // Generated Kotest FreeSpec test class
            val testClassName = "${baseName}GherkinTest"
            val escapedPath = iface.featurePath.replace("\"", "\\\"")
            appendLine("class $testClassName : FreeSpec({")
            appendLine("    gherkin(\"$escapedPath\", $stepsVarName)")
            appendLine("})")
        }
    }

    private fun StringBuilder.renderStepCall(
        step: GeneratedStep,
        rowClasses: List<GeneratedRowClass>,
        expr: String,
    ) {
        val keyword = step.originalKeyword

        // Check if this step has a DataTable (List<...> param)
        val listParam = step.params.firstOrNull { it.typeName.startsWith("List<") }
        val inlineParams = step.params.filter { it !== listParam }

        if (listParam != null) {
            // DataTable mapping step
            val rowClass = rowClasses.firstOrNull { it.name == listParam.typeName.removePrefix("List<").removeSuffix(">") }
            appendLine("                $keyword(\"$expr\") { params ->")
            if (rowClass != null) {
                appendLine("                    val rows = params.dataTable!!.rows.map { row ->")
                appendLine("                        ${rowClass.name}(")
                val assignments = rowClass.params.joinToString(",\n") { p ->
                    val accessor = when (p.typeName) {
                        "String" -> "row[\"${p.name}\"] ?: \"\""
                        "Int" -> "row[\"${p.name}\"]?.toIntOrNull() ?: 0"
                        "Long" -> "row[\"${p.name}\"]?.toLongOrNull() ?: 0L"
                        "Double" -> "row[\"${p.name}\"]?.toDoubleOrNull() ?: 0.0"
                        "Boolean" -> "row[\"${p.name}\"]?.toBooleanStrictOrNull() ?: false"
                        else -> "TODO(\"map row[\\\"${p.name}\\\"] to ${p.typeName}\")"
                    }
                    "                            ${p.name} = $accessor"
                }
                appendLine(assignments)
                appendLine("                        )")
                appendLine("                    }")
                append("                    ctx.${step.methodName}(")
                if (inlineParams.isNotEmpty()) {
                    append(inlineParams.mapIndexed { i, p -> "params.component${i + 1}() as ${p.typeName}" }.joinToString(", "))
                    append(", rows")
                } else {
                    append("rows")
                }
                appendLine(")")
            } else {
                // List<T> with no field info — fall back to raw DataTable rows
                append("                    ctx.${step.methodName}(")
                if (inlineParams.isNotEmpty()) {
                    append(inlineParams.mapIndexed { i, p -> "params.component${i + 1}() as ${p.typeName}" }.joinToString(", "))
                    append(", ")
                }
                appendLine("params.dataTable!!.rows as ${listParam.typeName})")
            }
            appendLine("                }")
        } else {
            // Inline params only — widen types for @BehaveCast and add conversion
            val destructure = step.params.mapIndexed { i, p ->
                val widening = if (i in step.castParams) wideningMap[step.castParams[i]] else null
                val destructType = widening?.second ?: p.typeName
                "p${i + 1}: $destructType"
            }.joinToString(", ")
            val args = step.params.mapIndexed { i, _ ->
                val narrowType = step.castParams[i]
                val widening = if (narrowType != null) wideningMap[narrowType] else null
                if (widening != null) {
                    widening.third.replace("\$p", "p${i + 1}")
                } else {
                    "p${i + 1}"
                }
            }.joinToString(", ")
            appendLine("                $keyword(\"$expr\") { ($destructure) ->")
            appendLine("                    ctx.${step.methodName}($args)")
            appendLine("                }")
        }
    }

    /**
     * Widen placeholders in the step expression for parameters annotated with @BehaveCast.
     * E.g., if param 0 has castParams[0] = "Int", replace the first {int} with {double}.
     */
    internal fun widenStepExpression(
        expr: String,
        castParams: Map<Int, String>,
        params: List<StepParam>,
    ): String {
        if (castParams.isEmpty()) return expr

        // Find all {placeholder} occurrences in order
        val placeholderRegex = Regex("\\{([^}]+)}")
        val matches = placeholderRegex.findAll(expr).toList()

        var result = expr
        // Process in reverse order to preserve indices
        var placeholderIdx = matches.size - 1
        for (match in matches.reversed()) {
            if (placeholderIdx in castParams) {
                val narrowType = castParams[placeholderIdx]!!
                val widening = wideningMap[narrowType]
                if (widening != null) {
                    val widerPlaceholder = widening.first
                    result = result.substring(0, match.range.first) +
                        "{$widerPlaceholder}" +
                        result.substring(match.range.last + 1)
                }
            }
            placeholderIdx--
        }

        return result
    }

    /** Escape regex special characters in literal step text (outside {} tokens). */
    fun escapeStepExpression(text: String): String {
        val specialChars = setOf('.', '(', ')', '[', ']', '^', '$', '*', '+', '?', '|', '\\')
        val sb = StringBuilder()
        var inPlaceholder = false
        for (ch in text) {
            when {
                ch == '{' -> { inPlaceholder = true; sb.append(ch) }
                ch == '}' -> { inPlaceholder = false; sb.append(ch) }
                inPlaceholder -> sb.append(ch)
                ch in specialChars -> sb.append("\\$ch")
                else -> sb.append(ch)
            }
        }
        return sb.toString()
    }

    /**
     * Replace "literal" and "<variable>" tokens with {string} for the step expression.
     * Must be applied before [replaceOutlineVariables] so that quoted outline variables
     * like "<answer>" become {string} rather than "{word}".
     */
    fun replaceQuotedLiterals(text: String): String =
        text.replace(Regex("\"[^\"]*\""), "{string}")

    /**
     * Replace standalone number literals with typed placeholders.
     * Doubles are matched first to prevent partial matches (e.g., 5.5 becoming {int}.5).
     * Numbers must be surrounded by whitespace (or at start/end of text) — no embedded digits.
     * Must be called AFTER [replaceQuotedLiterals] so numbers inside quotes are already consumed.
     * Does not touch numbers inside existing {placeholders}.
     */
    fun replaceNumberLiterals(text: String): String {
        var result = text
        result = result.replace(Regex("""(?<!\S)-?\d+\.\d+(?!\S)"""), "{double}")
        result = result.replace(Regex("""(?<!\S)-?\d+(?!\S)"""), "{int}")
        return result
    }

    /** Convert <variable> tokens in step text to {word} for the emitted step expression. */
    fun replaceOutlineVariables(text: String): String =
        text.replace(Regex("<([^>]+)>"), "{word}")

    /** Built-in placeholder → Kotlin type mapping. */
    val builtinTypes = mapOf(
        "string"  to "String",
        "int"     to "Int",
        "long"    to "Long",
        "float"   to "Float",
        "double"  to "Double",
        "word"    to "String",
        "boolean" to "Boolean",
    )

    /**
     * Widening map for @BehaveCast: narrow type → (wider placeholder, wider Kotlin type, conversion expression).
     * The conversion expression uses `$p` as a placeholder for the parameter variable name.
     */
    internal val wideningMap = mapOf(
        "Int" to Triple("double", "Double", "\$p.toInt()"),
        "Long" to Triple("double", "Double", "\$p.toLong()"),
        "Float" to Triple("double", "Double", "\$p.toFloat()"),
    )
}
