package io.mcol.behave.ksp

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec

/**
 * Generates Kotlin source text for the step definitions interface.
 *
 * The structural skeleton (file header, imports, data classes, the spec interface and its
 * suspend method signatures, the companion `steps()` factory, the generated top-level `val`
 * and the Kotest `*GherkinTest` class) is assembled with KotlinPoet. The step-routing bodies
 * inside the `steps { }` DSL are emitted as raw [CodeBlock]s built from literal text so that
 * fully-qualified converter call sites, `params[i] as T` casts and DataTable row mapping keep
 * exactly the same shape as before (KotlinPoet is not allowed to rewrite/shorten them).
 */
@Suppress("TooManyFunctions") // KotlinPoet assembly is split into small focused builder helpers
internal object CodeGenerator {
    data class TypeMapping(
        val placeholder: String, // e.g. "label" for {label}, or "" for field-based
        val typeName: String, // fully qualified type name
        val fields: List<String>, // field names for multi-field grouping; empty for placeholder mode
    )

    data class StepParam(
        val name: String,
        val typeName: String, // Kotlin type name (e.g. "String", "Int", "List<CatRow>")
    )

    data class ConverterInfo(
        val functionName: String, // simple name
        val qualifiedName: String, // fully qualified name (package.name)
        val returnType: String,
        val paramCount: Int,
    )

    data class GeneratedStep(
        val methodName: String,
        val params: List<StepParam>,
        val stepExpression: String, // regex-escaped pattern for the companion
        val originalKeyword: String,
        val originalText: String,
        val castParams: Map<Int, String> = emptyMap(), // param index → original narrow type (e.g. "Int")
        val typeConversions: Map<Int, String> = emptyMap(), // param index → fully qualified type name (e.g. "com.example.Item")
        val typeConverters: Map<Int, ConverterInfo> = emptyMap(), // param index → converter function and return type
        val hasDocString: Boolean = false, // true if the step carries a """/``` doc string (extra String param)
    )

    data class GeneratedRowClass(
        val name: String,
        val params: List<StepParam>,
        val shouldEmit: Boolean = true, // false for user-defined types that already exist
    )

    data class GeneratedInterface(
        val packageName: String,
        val interfaceName: String, // e.g. "LoginStepsSpec"
        val implementingClassName: String, // e.g. "LoginSteps"
        val featurePath: String, // e.g. "features/login.feature"
        val generateTest: Boolean, // when false, skip val + test class generation
        val hasScenarioRunner: Boolean, // when true, generate per-scenario runner variant
        val hasBeforeScenario: Boolean, // when true, register Before hook delegating to BeforeScenario
        val hasAfterScenario: Boolean, // when true, register After hook delegating to AfterScenario
        val steps: List<GeneratedStep>,
        val rowClasses: List<GeneratedRowClass>,
        // Fully-qualified names of @StepsMixin interfaces whose method signatures match steps
        // in this feature. The generated spec extends them so users don't redeclare bodies.
        val inheritedMixins: List<String> = emptyList(),
        // Generated method names that come from a mixin. Skipped in the abstract block but
        // still routed in the steps {} companion (the inherited method is called instead).
        val inheritedMethodNames: Set<String> = emptyList<String>().toSet(),
    )

    fun render(iface: GeneratedInterface): String {
        val fileBuilder = FileSpec.builder(iface.packageName, iface.interfaceName)
            .addFileComment("Generated by kotlin-behave KSP — do not edit")
            .addImport("io.kotest.core.spec.style", "FreeSpec")
            .addImport("io.mcol.behave.kotest", "gherkin")
        if (iface.hasScenarioRunner) {
            fileBuilder.addImport("io.mcol.behave.steps", "ScenarioRunner")
        }
        if (iface.hasBeforeScenario) {
            fileBuilder.addImport("io.mcol.behave.steps", "BeforeScenario")
        }
        if (iface.hasAfterScenario) {
            fileBuilder.addImport("io.mcol.behave.steps", "AfterScenario")
            fileBuilder.addImport("io.mcol.behave.steps", "ScenarioInfo")
        }

        // Row classes first (only emit auto-generated ones, not user-defined)
        for (row in iface.rowClasses.filter { it.shouldEmit }) {
            fileBuilder.addType(buildRowClass(row, iface.packageName))
        }

        fileBuilder.addType(buildSpecInterface(iface))

        val fileText = fileBuilder.build().toString()
        if (!iface.generateTest) return fileText

        // The generated top-level `val` and the Kotest `*GherkinTest` class are appended as
        // exact literal source. Their precise single-line shape (e.g.
        // `val generatedLoginSteps = LoginStepsSpec.steps { LoginSteps() }`) is part of the
        // generator's published contract, so we keep full control of their formatting rather
        // than letting KotlinPoet add an explicit property type and reflow.
        return buildString {
            append(fileText)
            if (!fileText.endsWith("\n")) appendLine()
            appendLine()
            append(buildGeneratedStepsAndTest(iface))
        }
    }

    private fun buildRowClass(row: GeneratedRowClass, defaultPackage: String): TypeSpec {
        val ctor = FunSpec.constructorBuilder()
        val builder = TypeSpec.classBuilder(row.name).addModifiers(KModifier.DATA)
        for (param in row.params) {
            ctor.addParameter(param.name, anyType(param.typeName, defaultPackage))
            builder.addProperty(
                PropertySpec.builder(param.name, anyType(param.typeName, defaultPackage))
                    .initializer(param.name)
                    .build(),
            )
        }
        return builder.primaryConstructor(ctor.build()).build()
    }

    private fun buildSpecInterface(iface: GeneratedInterface): TypeSpec {
        val builder = TypeSpec.interfaceBuilder(iface.interfaceName)
        for (mixin in iface.inheritedMixins) {
            builder.addSuperinterface(classNameOf(mixin, iface.packageName))
        }

        for (step in iface.steps) {
            if (step.methodName in iface.inheritedMethodNames) continue
            builder.addFunction(buildStepSignature(step, iface.packageName))
        }

        builder.addType(buildCompanion(iface))
        return builder.build()
    }

    /** Fully-qualified name of the generated spec interface (so KotlinPoet doesn't self-import it). */
    private fun specFqn(iface: GeneratedInterface): String {
        if (iface.packageName.isEmpty()) return iface.interfaceName
        return "${iface.packageName}.${iface.interfaceName}"
    }

    private fun buildStepSignature(step: GeneratedStep, defaultPackage: String): FunSpec {
        val skippedIndices = consumedConverterIndices(step)
        val fn = FunSpec.builder(step.methodName)
            .addModifiers(KModifier.SUSPEND, KModifier.ABSTRACT)
            .addKdoc("%L %L", step.originalKeyword, step.originalText)
        step.params.forEachIndexed { idx, param ->
            if (idx in skippedIndices) return@forEachIndexed
            val paramType = step.typeConversions[idx] ?: step.typeConverters[idx]?.returnType ?: param.typeName
            fn.addParameter(param.name, anyType(paramType, defaultPackage))
        }
        if (step.hasDocString) fn.addParameter("docString", anyType("String", defaultPackage))
        return fn.build()
    }

    private fun buildCompanion(iface: GeneratedInterface): TypeSpec {
        val specFqn = specFqn(iface)
        val factoryFn = FunSpec.builder("steps")
            .addParameter("factory", anyType("() -> $specFqn", iface.packageName))
            .returns(anyType("io.mcol.behave.steps.StepDefinitions<$specFqn>", iface.packageName))
            .addCode(buildStepsBody(iface))
            .build()
        return TypeSpec.companionObjectBuilder().addFunction(factoryFn).build()
    }

    /** Body of the companion `steps(factory) { ... }` factory, assembled as literal source. */
    private fun buildStepsBody(iface: GeneratedInterface): CodeBlock {
        val body = StringBuilder()
        body.appendLine("return io.mcol.behave.steps.steps(factory) {")
        for (step in iface.steps) {
            val keyword = step.originalKeyword
            val widenedExpr = widenStepExpression(step.stepExpression, step.castParams, step.params)
            val expr = widenedExpr.replace("\"", "\\\"")
            if (step.params.isEmpty() && !step.hasDocString) {
                body.appendLine("    $keyword(\"$expr\") { ctx.${step.methodName}() }")
            } else if (step.params.isEmpty()) {
                body.appendLine("    $keyword(\"$expr\") { params -> ctx.${step.methodName}(params.docString ?: \"\") }")
            } else {
                renderStepCall(body, step, iface.rowClasses, expr)
            }
        }
        body.appendLine("}")
        // Emit as a single literal block; KotlinPoet must not reflow or escape it.
        return CodeBlock.of("%L", body.toString())
    }

    /**
     * Emit the generated top-level `val` (the step-definitions instance) and the Kotest
     * `*GherkinTest` class as literal source. Only called when `generateTest` is true.
     */
    private fun buildGeneratedStepsAndTest(iface: GeneratedInterface): String {
        val baseName = iface.implementingClassName.removeSuffix("Steps")
        val stepsVarName = "generated${baseName}Steps"
        val out = StringBuilder()

        // Generated step definitions instance
        val hasHooks = iface.hasBeforeScenario || iface.hasAfterScenario
        if (hasHooks) {
            out.appendLine("val $stepsVarName = ${iface.interfaceName}.steps { ${iface.implementingClassName}() }.also { defs ->")
            if (iface.hasBeforeScenario) {
                out.appendLine("    defs.stepBuilder.Before { ctx -> (ctx as BeforeScenario).beforeScenario() }")
            }
            if (iface.hasAfterScenario) {
                out.appendLine("    defs.stepBuilder.After { info: ScenarioInfo, ctx -> (ctx as AfterScenario).afterScenario(info) }")
            }
            out.appendLine("}")
        } else {
            out.appendLine("val $stepsVarName = ${iface.interfaceName}.steps { ${iface.implementingClassName}() }")
        }
        out.appendLine()

        // Generated Kotest FreeSpec test class
        val testClassName = "${baseName}GherkinTest"
        val escapedPath = iface.featurePath.replace("\"", "\\\"")
        out.appendLine("class $testClassName : FreeSpec({")
        if (iface.hasScenarioRunner) {
            out.appendLine("    gherkin(\"$escapedPath\", $stepsVarName) { ctx, run ->")
            out.appendLine("        (ctx as ScenarioRunner).runScenario(ctx, run)")
            out.appendLine("    }")
        } else {
            out.appendLine("    gherkin(\"$escapedPath\", $stepsVarName)")
        }
        out.appendLine("})")
        return out.toString()
    }

    private fun consumedConverterIndices(step: GeneratedStep): Set<Int> {
        val skipped = mutableSetOf<Int>()
        for ((idx, converter) in step.typeConverters) {
            if (converter.paramCount > 1) {
                for (i in 1 until converter.paramCount) skipped.add(idx + i)
            }
        }
        return skipped
    }

    private fun renderStepCall(
        out: StringBuilder,
        step: GeneratedStep,
        rowClasses: List<GeneratedRowClass>,
        expr: String,
    ) {
        val keyword = step.originalKeyword
        // A doc string becomes a trailing `params.docString ?: ""` argument on every call site.
        val docArg = if (step.hasDocString) ", params.docString ?: \"\"" else ""

        // Check if this step has a DataTable (List<...> param)
        val listParam = step.params.firstOrNull { it.typeName.startsWith("List<") }
        val inlineParams = step.params.filter { it !== listParam }

        if (listParam != null) {
            // DataTable mapping step
            val rowClass = rowClasses.firstOrNull { it.name == listParam.typeName.removePrefix("List<").removeSuffix(">") }
            out.appendLine("    $keyword(\"$expr\") { params ->")
            if (rowClass != null) {
                out.appendLine("        val rows = params.dataTable!!.rows.map { row ->")
                out.appendLine("            ${rowClass.name}(")
                val assignments =
                    rowClass.params.joinToString(",\n") { p ->
                        val accessor =
                            when (p.typeName) {
                                "String" -> "row[\"${p.name}\"] ?: \"\""
                                "Int" -> "row[\"${p.name}\"]?.toIntOrNull() ?: 0"
                                "Long" -> "row[\"${p.name}\"]?.toLongOrNull() ?: 0L"
                                "Double" -> "row[\"${p.name}\"]?.toDoubleOrNull() ?: 0.0"
                                "Boolean" -> "row[\"${p.name}\"]?.toBooleanStrictOrNull() ?: false"
                                else -> "TODO(\"map row[\\\"${p.name}\\\"] to ${p.typeName}\")"
                            }
                        "                ${p.name} = $accessor"
                    }
                out.appendLine(assignments)
                out.appendLine("            )")
                out.appendLine("        }")
                out.append("        ctx.${step.methodName}(")
                if (inlineParams.isNotEmpty()) {
                    out.append(inlineParams.mapIndexed { i, p -> "params[$i] as ${p.typeName}" }.joinToString(", "))
                    out.append(", rows")
                } else {
                    out.append("rows")
                }
                out.appendLine("$docArg)")
            } else {
                // List<T> with no field info — fall back to raw DataTable rows
                out.append("        ctx.${step.methodName}(")
                if (inlineParams.isNotEmpty()) {
                    out.append(inlineParams.mapIndexed { i, p -> "params[$i] as ${p.typeName}" }.joinToString(", "))
                    out.append(", ")
                }
                out.appendLine("params.dataTable!!.rows as ${listParam.typeName}$docArg)")
            }
            out.appendLine("    }")
        } else {
            // Inline params only — use indexed access for unlimited parameters
            out.appendLine("    $keyword(\"$expr\") { params ->")
            // Track which param indices are consumed by multi-param converters
            val consumedIndices = consumedConverterIndices(step)

            step.params.forEachIndexed { i, p ->
                if (i in consumedIndices) return@forEachIndexed // Skip consumed parameters

                val narrowType = step.castParams[i]
                val widening = if (narrowType != null) wideningMap[narrowType] else null
                val destructType = widening?.second ?: p.typeName
                val conversion = step.typeConversions[i]
                val converter = step.typeConverters[i]

                if (converter != null) {
                    // Always call via the fully qualified name as a regular function — works
                    // both for non-extension `fun convert(s: String)` and extension
                    // `fun String.convert()` (Kotlin allows extension fns to be called
                    // with the receiver as the first argument when accessed by FQN).
                    // The old extension-style `(params[i] as String).convert()` broke for
                    // non-extension converters because it implied a `String.convert()` ext fn.
                    val converterParams = (0 until converter.paramCount).joinToString(", ") { idx ->
                        "params[${i + idx}] as ${step.params.getOrNull(i + idx)?.typeName ?: "String"}"
                    }
                    out.appendLine("        val p${i + 1} = ${converter.qualifiedName}($converterParams)")
                } else if (conversion != null) {
                    // Use enum valueOf()
                    out.appendLine("        val p${i + 1} = $conversion.valueOf((params[$i] as String).uppercase())")
                } else {
                    out.appendLine("        val p${i + 1} = params[$i] as $destructType")
                }
            }
            val args =
                step.params
                    .mapIndexed { i, _ ->
                        if (i in consumedIndices) {
                            null
                        } else {
                            val narrowType = step.castParams[i]
                            val widening = if (narrowType != null) wideningMap[narrowType] else null
                            if (widening != null) {
                                widening.third.replace("\$p", "p${i + 1}")
                            } else {
                                "p${i + 1}"
                            }
                        }
                    }.filterNotNull().joinToString(", ")
            val finalArgs = when {
                !step.hasDocString -> args
                args.isEmpty() -> "params.docString ?: \"\""
                else -> "$args$docArg"
            }
            out.appendLine("        ctx.${step.methodName}($finalArgs)")
            out.appendLine("    }")
        }
    }

    /**
     * Widen placeholders in the step expression for parameters annotated with @BehaveCast.
     * E.g., if param 0 has castParams[0] = "Int", replace the first {int} with {double}.
     */
    internal fun widenStepExpression(
        expr: String,
        castParams: Map<Int, String>,
        params: List<StepParam>,
    ): String {
        if (castParams.isEmpty()) return expr

        // Find all {placeholder} occurrences in order
        val placeholderRegex = Regex("\\{([^}]+)}")
        val matches = placeholderRegex.findAll(expr).toList()

        var result = expr
        // Process in reverse order to preserve indices
        var placeholderIdx = matches.size - 1
        for (match in matches.reversed()) {
            if (placeholderIdx in castParams) {
                val narrowType = castParams[placeholderIdx]!!
                val widening = wideningMap[narrowType]
                if (widening != null) {
                    val widerPlaceholder = widening.first
                    result = result.substring(0, match.range.first) +
                        "{$widerPlaceholder}" +
                        result.substring(match.range.last + 1)
                }
            }
            placeholderIdx--
        }

        return result
    }

    /** Escape regex special characters in literal step text (outside {} tokens). */
    fun escapeStepExpression(text: String): String {
        val specialChars = setOf('.', '(', ')', '[', ']', '^', '$', '*', '+', '?', '|', '\\')
        val sb = StringBuilder()
        var inPlaceholder = false
        for (ch in text) {
            when {
                ch == '{' -> {
                    inPlaceholder = true
                    sb.append(ch)
                }
                ch == '}' -> {
                    inPlaceholder = false
                    sb.append(ch)
                }
                inPlaceholder -> sb.append(ch)
                ch in specialChars -> sb.append("\\$ch")
                else -> sb.append(ch)
            }
        }
        return sb.toString()
    }

    /**
     * Replace "literal" and "<variable>" tokens with {string} for the step expression.
     * Must be applied before [replaceOutlineVariables] so that quoted outline variables
     * like "<answer>" become {string} rather than "{word}".
     */
    fun replaceQuotedLiterals(text: String): String = text.replace(Regex("\"[^\"]*\""), "{string}")

    /**
     * Replace standalone number literals with typed placeholders.
     * Doubles are matched first to prevent partial matches (e.g., 5.5 becoming {int}.5).
     * Numbers must be surrounded by whitespace (or at start/end of text) — no embedded digits.
     * Must be called AFTER [replaceQuotedLiterals] so numbers inside quotes are already consumed.
     * Does not touch numbers inside existing {placeholders}.
     */
    fun replaceNumberLiterals(text: String): String {
        var result = text
        result = result.replace(Regex("""(?<!\S)-?\d+\.\d+(?!\S)"""), "{double}")
        result = result.replace(Regex("""(?<!\S)-?\d+(?!\S)"""), "{int}")
        return result
    }

    /** Convert <variable> tokens in step text to {word} for the emitted step expression. */
    fun replaceOutlineVariables(text: String): String = text.replace(Regex("<([^>]+)>"), "{word}")

    /**
     * Convert <variable> tokens to typed placeholders based on inferred Examples-table types.
     * A variable whose Examples values are consistently numeric/boolean becomes the matching
     * builtin placeholder ({int}, {double}, {boolean}, …) so the runtime TypeRegistry converts
     * it to the real type. Variables without a known typed inference fall back to {word} (String).
     *
     * [varTypes] maps variable name → Kotlin type name (e.g. "status" -> "Int").
     */
    fun replaceOutlineVariablesTyped(text: String, varTypes: Map<String, String>): String = text.replace(Regex("<([^>]+)>")) { m ->
        val name = m.groupValues[1]
        val placeholder = io.mcol.behave.gherkin.GherkinTypes.kotlinToPlaceholder[varTypes[name]] ?: "word"
        "{$placeholder}"
    }

    /** Built-in placeholder → Kotlin type mapping (shared source of truth). */
    val builtinTypes = io.mcol.behave.gherkin.GherkinTypes.placeholderToKotlin

    /**
     * Widening map for @BehaveCast: narrow type → (wider placeholder, wider Kotlin type, conversion expression).
     * The conversion expression uses `$p` as a placeholder for the parameter variable name.
     */
    internal val wideningMap =
        mapOf(
            "Int" to Triple("double", "Double", "\$p.toInt()"),
            "Long" to Triple("double", "Double", "\$p.toLong()"),
            "Float" to Triple("double", "Double", "\$p.toFloat()"),
        )

    /**
     * Parse a plain-text type expression (the form the rest of the pipeline produces, e.g.
     * "String", "List<io.mcol.Foo>", "() -> Bar", "io.mcol.behave.steps.StepDefinitions<FooSpec>")
     * into a KotlinPoet [TypeName] so that signatures and properties can be modelled structurally.
     */
    private fun anyType(typeName: String, defaultPackage: String): TypeName {
        val trimmed = typeName.trim()

        // Function type: "(A, B) -> R"
        val arrow = trimmed.indexOf("->")
        if (trimmed.startsWith("(") && arrow >= 0) {
            val paramsPart = trimmed.substring(1, trimmed.indexOf(')'))
            val returnPart = trimmed.substring(arrow + 2).trim()
            val paramTypes = splitTopLevel(paramsPart)
                .filter { it.isNotBlank() }
                .map { anyType(it, defaultPackage) }
            return LambdaTypeName.get(
                parameters = paramTypes.toTypedArray(),
                returnType = anyType(returnPart, defaultPackage),
            )
        }

        // Generic type: "Outer<A, B>"
        val lt = trimmed.indexOf('<')
        if (lt >= 0 && trimmed.endsWith(">")) {
            val rawName = trimmed.substring(0, lt)
            val argsPart = trimmed.substring(lt + 1, trimmed.length - 1)
            val args = splitTopLevel(argsPart).map { anyType(it, defaultPackage) }
            return classNameOf(rawName, defaultPackage).parameterizedBy(args)
        }

        return classNameOf(trimmed, defaultPackage)
    }

    /** Split a comma-separated type list, ignoring commas nested inside `<...>`. */
    private fun splitTopLevel(text: String): List<String> {
        val parts = mutableListOf<String>()
        var depth = 0
        val current = StringBuilder()
        for (ch in text) {
            when (ch) {
                '<' -> {
                    depth++
                    current.append(ch)
                }
                '>' -> {
                    depth--
                    current.append(ch)
                }
                ',' -> if (depth == 0) {
                    parts.add(current.toString().trim())
                    current.clear()
                } else {
                    current.append(ch)
                }
                else -> current.append(ch)
            }
        }
        if (current.isNotBlank()) parts.add(current.toString().trim())
        return parts
    }

    /** Bare Kotlin builtin simple names that live in `kotlin` / `kotlin.collections`. */
    private val kotlinBuiltins = mapOf(
        "String" to "kotlin",
        "Int" to "kotlin",
        "Long" to "kotlin",
        "Short" to "kotlin",
        "Byte" to "kotlin",
        "Float" to "kotlin",
        "Double" to "kotlin",
        "Boolean" to "kotlin",
        "Char" to "kotlin",
        "Any" to "kotlin",
        "Unit" to "kotlin",
        "Number" to "kotlin",
        "List" to "kotlin.collections",
        "Map" to "kotlin.collections",
        "Set" to "kotlin.collections",
        "MutableList" to "kotlin.collections",
        "MutableMap" to "kotlin.collections",
        "MutableSet" to "kotlin.collections",
        "Collection" to "kotlin.collections",
    )

    /**
     * Resolve a type-name string into a [ClassName].
     *  - dotted names keep their explicit package;
     *  - bare Kotlin builtins (String, Int, List, …) resolve to `kotlin` / `kotlin.collections`;
     *  - any other bare name (an auto-generated `*Row` class, etc.) is assumed to live in the
     *    file's own [defaultPackage] so KotlinPoet emits it as a same-package reference with no
     *    spurious `import <Name>`.
     */
    private fun classNameOf(qualified: String, defaultPackage: String): ClassName {
        val pkg = qualified.substringBeforeLast('.', "")
        val simple = qualified.substringAfterLast('.')
        if (pkg.isNotEmpty()) return ClassName(pkg, simple)
        kotlinBuiltins[simple]?.let { return ClassName(it, simple) }
        return ClassName(defaultPackage, simple)
    }
}
