package io.mcol.behave.ksp

/**
 * Generates Kotlin source text for the step definitions interface.
 */
internal object CodeGenerator {

    data class TypeMapping(
        val placeholder: String,   // e.g. "label" for {label}, or "" for field-based
        val typeName: String,      // fully qualified type name
        val fields: List<String>,  // field names for multi-field grouping; empty for placeholder mode
    )

    data class StepParam(
        val name: String,
        val typeName: String,  // Kotlin type name (e.g. "String", "Int", "List<CatRow>")
    )

    data class GeneratedStep(
        val methodName: String,
        val params: List<StepParam>,
        val stepExpression: String,  // regex-escaped pattern for the companion
        val originalKeyword: String,
        val originalText: String,
    )

    data class GeneratedRowClass(
        val name: String,
        val params: List<StepParam>,
    )

    data class GeneratedInterface(
        val packageName: String,
        val interfaceName: String,      // e.g. "LoginStepsSpec"
        val implementingClassName: String, // e.g. "LoginSteps"
        val steps: List<GeneratedStep>,
        val rowClasses: List<GeneratedRowClass>,
    )

    fun render(iface: GeneratedInterface): String = buildString {
        appendLine("// Generated by kotlin-behave KSP — do not edit")
        appendLine("package ${iface.packageName}")
        appendLine()

        // Row classes first
        for (row in iface.rowClasses) {
            append("data class ${row.name}(")
            append(row.params.joinToString(", ") { "val ${it.name}: ${it.typeName}" })
            appendLine(")")
            appendLine()
        }

        appendLine("interface ${iface.interfaceName} {")
        appendLine()

        for (step in iface.steps) {
            appendLine("    // ${step.originalKeyword} ${step.originalText}")
            if (step.params.isEmpty()) {
                appendLine("    suspend fun ${step.methodName}()")
            } else {
                val paramList = step.params.joinToString(", ") { "${it.name}: ${it.typeName}" }
                appendLine("    suspend fun ${step.methodName}($paramList)")
            }
            appendLine()
        }

        appendLine("    companion object {")
        appendLine("        fun steps(factory: () -> ${iface.interfaceName}): io.mcol.behave.steps.StepDefinitions<${iface.interfaceName}> =")
        appendLine("            io.mcol.behave.steps.steps(factory) {")

        for (step in iface.steps) {
            val keyword = step.originalKeyword
            val expr = step.stepExpression
            if (step.params.isEmpty()) {
                appendLine("                $keyword(\"$expr\") { ctx.${step.methodName}() }")
            } else {
                renderStepCall(step, iface.rowClasses)
            }
        }

        appendLine("            }")
        appendLine("    }")
        appendLine("}")
    }

    private fun StringBuilder.renderStepCall(
        step: GeneratedStep,
        rowClasses: List<GeneratedRowClass>,
    ) {
        val keyword = step.originalKeyword
        val expr = step.stepExpression

        // Check if this step has a DataTable (List<...> param)
        val listParam = step.params.firstOrNull { it.typeName.startsWith("List<") }
        val inlineParams = step.params.filter { it !== listParam }

        if (listParam != null) {
            // DataTable mapping step
            val rowClass = rowClasses.firstOrNull { it.name == listParam.typeName.removePrefix("List<").removeSuffix(">") }
            appendLine("                $keyword(\"$expr\") { params ->")
            if (rowClass != null) {
                appendLine("                    val rows = params.dataTable!!.rows.map { row ->")
                appendLine("                        ${rowClass.name}(")
                val assignments = rowClass.params.joinToString(",\n") { p ->
                    "                            ${p.name} = TODO(\"map row[\\\"${p.name}\\\"] to ${p.typeName}\")"
                }
                appendLine(assignments)
                appendLine("                        )")
                appendLine("                    }")
                append("                    ctx.${step.methodName}(")
                if (inlineParams.isNotEmpty()) {
                    append(inlineParams.mapIndexed { i, p -> "params.component${i + 1}() as ${p.typeName}" }.joinToString(", "))
                    append(", rows")
                } else {
                    append("rows")
                }
                appendLine(")")
            } else {
                // List<T> with a registered table type — rows are mapped by the TypeRegistry
                append("                    ctx.${step.methodName}(")
                if (inlineParams.isNotEmpty()) {
                    append(inlineParams.mapIndexed { i, p -> "params.component${i + 1}() as ${p.typeName}" }.joinToString(", "))
                    append(", ")
                }
                appendLine("params.component${inlineParams.size + 1}() as ${listParam.typeName})")
            }
            appendLine("                }")
        } else {
            // Inline params only
            val destructure = step.params.mapIndexed { i, p -> "p${i + 1}: ${p.typeName}" }.joinToString(", ")
            val args = step.params.indices.joinToString(", ") { "p${it + 1}" }
            appendLine("                $keyword(\"$expr\") { ($destructure) ->")
            appendLine("                    ctx.${step.methodName}($args)")
            appendLine("                }")
        }
    }

    /** Escape regex special characters in literal step text (outside {} tokens). */
    fun escapeStepExpression(text: String): String {
        val specialChars = setOf('.', '(', ')', '[', ']', '^', '$', '*', '+', '?', '|', '\\')
        val sb = StringBuilder()
        var inPlaceholder = false
        for (ch in text) {
            when {
                ch == '{' -> { inPlaceholder = true; sb.append(ch) }
                ch == '}' -> { inPlaceholder = false; sb.append(ch) }
                inPlaceholder -> sb.append(ch)
                ch in specialChars -> sb.append("\\$ch")
                else -> sb.append(ch)
            }
        }
        return sb.toString()
    }

    /** Convert <variable> tokens in step text to {word} for the emitted step expression. */
    fun replaceOutlineVariables(text: String): String =
        text.replace(Regex("<([^>]+)>"), "{word}")

    /** Built-in placeholder → Kotlin type mapping. */
    val builtinTypes = mapOf(
        "string" to "String",
        "int"    to "Int",
        "long"   to "Long",
        "float"  to "Float",
        "double" to "Double",
        "word"   to "String",
    )
}
