package io.mcol.behave.ksp

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class CodeGeneratorTest {

    @Test
    fun `escapeStepExpression escapes dots`() {
        assertEquals("I have a collection \\.", CodeGenerator.escapeStepExpression("I have a collection ."))
    }

    @Test
    fun `escapeStepExpression does not escape inside placeholders`() {
        assertEquals("value is {int}", CodeGenerator.escapeStepExpression("value is {int}"))
    }

    @Test
    fun `escapeStepExpression escapes parens outside placeholders`() {
        assertEquals("click \\(ok\\)", CodeGenerator.escapeStepExpression("click (ok)"))
    }

    @Test
    fun `replaceOutlineVariables converts variable tokens to word`() {
        assertEquals("I am logged in as {word}", CodeGenerator.replaceOutlineVariables("I am logged in as <role>"))
    }

    @Test
    fun `replaceQuotedLiterals converts quoted literal to string placeholder`() {
        assertEquals("I see the question word {string}", CodeGenerator.replaceQuotedLiterals("I see the question word \"pies\""))
    }

    @Test
    fun `replaceQuotedLiterals converts quoted outline variable to string placeholder`() {
        assertEquals("I type {string} in the answer field", CodeGenerator.replaceQuotedLiterals("I type \"<answer>\" in the answer field"))
    }

    @Test
    fun `replaceQuotedLiterals then replaceOutlineVariables handles unquoted variable`() {
        val text = "I see <type> feedback"
        val result = CodeGenerator.replaceOutlineVariables(CodeGenerator.replaceQuotedLiterals(text))
        assertEquals("I see {word} feedback", result)
    }

    @Test
    fun `renders interface with no-param method`() {
        val iface = CodeGenerator.GeneratedInterface(
            packageName = "com.example",
            interfaceName = "LoginStepsSpec",
            implementingClassName = "LoginSteps",
            steps = listOf(
                CodeGenerator.GeneratedStep(
                    methodName = "givenIAmOnTheLoginPage",
                    params = emptyList(),
                    stepExpression = "I am on the login page",
                    originalKeyword = "Given",
                    originalText = "I am on the login page",
                )
            ),
            rowClasses = emptyList(),
        )
        val source = CodeGenerator.render(iface)
        assertTrue(source.contains("interface LoginStepsSpec"))
        assertTrue(source.contains("suspend fun givenIAmOnTheLoginPage()"))
        assertTrue(source.contains("companion object"))
        assertTrue(source.contains("fun steps(factory: () -> LoginStepsSpec)"))
        assertTrue(source.contains("ctx.givenIAmOnTheLoginPage()"))
    }

    @Test
    fun `renders interface with typed params`() {
        val iface = CodeGenerator.GeneratedInterface(
            packageName = "com.example",
            interfaceName = "StepsSpec",
            implementingClassName = "Steps",
            steps = listOf(
                CodeGenerator.GeneratedStep(
                    methodName = "whenIEnterAsUsername",
                    params = listOf(CodeGenerator.StepParam("string", "String")),
                    stepExpression = "I enter {string} as username",
                    originalKeyword = "When",
                    originalText = "I enter {string} as username",
                )
            ),
            rowClasses = emptyList(),
        )
        val source = CodeGenerator.render(iface)
        assertTrue(source.contains("suspend fun whenIEnterAsUsername(string: String)"))
        assertTrue(source.contains("ctx.whenIEnterAsUsername("))
    }

    @Test
    fun `rendered source includes package declaration`() {
        val iface = CodeGenerator.GeneratedInterface(
            packageName = "io.mcol.test",
            interfaceName = "FooSpec",
            implementingClassName = "Foo",
            steps = emptyList(),
            rowClasses = emptyList(),
        )
        assertTrue(CodeGenerator.render(iface).startsWith("// Generated by kotlin-behave KSP"))
        assertTrue(CodeGenerator.render(iface).contains("package io.mcol.test"))
    }

    @Test
    fun `builtinTypes maps standard placeholders`() {
        assertEquals("String", CodeGenerator.builtinTypes["string"])
        assertEquals("Int", CodeGenerator.builtinTypes["int"])
        assertEquals("Long", CodeGenerator.builtinTypes["long"])
        assertEquals("Float", CodeGenerator.builtinTypes["float"])
        assertEquals("Double", CodeGenerator.builtinTypes["double"])
        assertEquals("String", CodeGenerator.builtinTypes["word"])
    }
}
